version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: vaccine_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./api/model/vaccine_hesitancy_model.keras:/app/api/model/vaccine_hesitancy_model.keras  # ✅ Mount clean file from host
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
