# Generated by Django 5.1.3 on 2025-07-18 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RespondentsInfo',
            fields=[
                ('user_id', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('age', models.CharField(choices=[('<20', '<20'), ('20-30', '20-30'), ('30-50', '30-50'), ('>50', '>50')], max_length=5)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('marital_status', models.CharField(choices=[('Unmarried', 'Unmarried'), ('Married', 'Married')], max_length=10)),
                ('no_of_children', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('>2', '>2')], max_length=10)),
                ('place', models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], max_length=10)),
                ('qualification', models.CharField(choices=[('Tertiary Education', 'Tertiary Education'), ('Primary/Secondary', 'Primary/Secondary'), ('Higher Secondary', 'Higher Secondary'), ('Higher Education', 'Higher Education')], max_length=50)),
                ('job', models.CharField(choices=[('Business', 'Business'), ('Clerical Job', 'Clerical Job'), ('Daily Earners', 'Daily Earners'), ('Housewife', 'Housewife'), ('Professional (Eg. Teachers, Engineers, Dr. Pharmacist etc)', 'Professional (Eg. Teachers, Engineers, Dr. Pharmacist etc)'), ('Student', 'Student')], max_length=100)),
            ],
            options={
                'db_table': 'respondents_info_real',
            },
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('user_id', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pages.respondentsinfo')),
                ('question1', models.CharField(db_column='Question1', max_length=20)),
                ('question2', models.CharField(db_column='Question2', max_length=20)),
                ('question3', models.CharField(db_column='Question3', max_length=20)),
                ('question4', models.CharField(db_column='Question4', max_length=20)),
                ('question5', models.CharField(db_column='Question5', max_length=20)),
                ('question6', models.CharField(db_column='Question6', max_length=20)),
                ('question7', models.CharField(db_column='Question7', max_length=20)),
                ('question8', models.CharField(db_column='Question8', max_length=20)),
                ('question9', models.CharField(db_column='Question9', max_length=20)),
                ('question10', models.CharField(db_column='Question10', max_length=20)),
                ('question11', models.CharField(db_column='Question11', max_length=20)),
                ('question12', models.CharField(db_column='Question12', max_length=20)),
                ('question13', models.CharField(db_column='Question13', max_length=20)),
                ('question14', models.CharField(db_column='Question14', max_length=20)),
                ('question15', models.CharField(db_column='Question15', max_length=20)),
                ('question16', models.CharField(db_column='Question16', max_length=20)),
                ('question17', models.CharField(db_column='Question17', max_length=20)),
                ('question18', models.CharField(db_column='Question18', max_length=20)),
                ('question19', models.CharField(db_column='Question19', max_length=20)),
                ('question20', models.CharField(db_column='Question20', max_length=20)),
                ('question21', models.CharField(db_column='Question21', max_length=20)),
                ('question22', models.CharField(db_column='Question22', max_length=20)),
                ('question23', models.CharField(db_column='Question23', max_length=20)),
                ('question24', models.CharField(db_column='Question24', max_length=20)),
                ('question25', models.CharField(db_column='Question25', max_length=20)),
                ('question26', models.CharField(db_column='Question26', max_length=20)),
                ('question27', models.CharField(db_column='Question27', max_length=20)),
                ('question28', models.CharField(db_column='Question28', max_length=20)),
                ('question29', models.CharField(db_column='Question29', max_length=20)),
                ('question30', models.CharField(db_column='Question30', max_length=20)),
                ('hesitancy_result', models.CharField(blank=True, db_column='HesitancyResult', max_length=20, null=True)),
                ('hesitancy_score', models.FloatField(blank=True, db_column='HesitancyScore', null=True)),
            ],
            options={
                'db_table': 'responses',
            },
        ),
    ]
