name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:14
        env:
          POSTGRES_DB: vaccine_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user -d vaccine_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_NAME: vaccine_db
      DB_USER: user
      DB_PASSWORD: pass
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: test-secret-key

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name:  Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name:  Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name:  Print PostgreSQL container logs
        run: |
          echo "PostgreSQL container logs:"
          docker logs $(docker ps -q --filter "ancestor=postgres:14") || true

      - name: 🔄 Run migrations and tests
        run: |
          python manage.py migrate
          python manage.py test
